---
title: "Seoul Bike Project"
output: html_document
---

```{r}
# call necessary packages
library(ggplot2)
library(dplyr)
library(reshape2)
library(tidyr)
library(raster)
library(ggmap)

# read the .csv file
df_raw <- read.csv("/Users/owlbemi/seoul_bike/서울특별시 공공자전거 외국인 대여정보(월별)_23.1-6.csv", fileEncoding = "CP949", encoding = "UTF-8")

df_location <- read.csv("/Users/owlbemi/seoul_bike/공공자전거 대여소 정보(23.06월 기준).csv", fileEncoding = "CP949", encoding = "UTF-8")

df_pop <- read.csv("/Users/owlbemi/seoul_bike/주민등록인구_20230915055038.csv")

# data cleaning
df_raw <- na.omit(df_raw)
summary(df_raw)

df_split <- strsplit(df_raw$대여소, '\\.')
df_split <- do.call(rbind.data.frame, df_split)

df_raw$`대여소` <- df_split$`c...해공도서관앞.....합정역.1번출구.앞.....합정역.7번출구.앞...`
df_raw$`대여소` <- trimws(df_raw$`대여소`)

df_location <- df_location %>% dplyr::select(-("운영.방식":"X.14"))
df_location <- df_location %>% dplyr::select(-("설치.시기":"X.3"))

colnames(df_location) <- c("대여소.번호", "대여소.명", "소재지", "주소", "북위", "동경")

df_location <- na.omit(df_location)
df_location$`북위` <- as.numeric(df_location$`북위`)
df_location$`동경` <- as.numeric(df_location$`동경`)

summary(df_location)

df_pop <- df_pop %>% select(-c("동별.1.", "X2023.1.4", "X2023.1.4.4", "X2023.2.4"))
df_pop <- df_pop %>% select(-("X2023.1.4.1":"X2023.1.4.5"))
df_pop <- df_pop[-1,]
df_pop <- as.data.frame(df_pop)

colnames(df_pop) <- c("동별", "합계", "한국인(명)", "외국인(명)", "인구밀도")

df_pop <- df_pop %>% select(-("인구밀도"))
```
```{r}
# exploratory analysis (EDA)
# 지역별 빈도수
loc_freq <- ggplot(df_location, aes(x = df_location$소재지)) +
  geom_bar() +
  labs(title = "서울시 자치구별 대여소 빈도수 (~2023)", x = "소재 자치구", y = "빈도수") +
  theme_linedraw()
loc_freq

# 송파구가 가장 많은 대여소를 가짐

# 대여건수 vs 반납건수
# max / min rental and return index
max_rent <- which.max(df_raw$`대여건수`)
min_rent <- which.min(df_raw$`대여건수`)

max_return <- which.max(df_raw$`반납건수`)
min_return <- which.min(df_raw$`반납건수`)

# location of those index
max_rent_loc <- df_raw$`대여소`[max_rent]
min_rent_loc <- df_raw$`대여소`[min_rent]

max_return_loc <- df_raw$`대여소`[max_return]
min_return_loc <- df_raw$`대여소`[min_return]

df_minmax <- df_raw[c(max_rent, min_rent, max_return, min_return),]
head(df_minmax)

# convert to long from data
df_minmax <- gather(df_minmax, key = var, value = value, 대여건수, 반납건수)
df_minmax <- unique(df_minmax)

# 2023년 6월 여의나루가 가장 많은 대여건수 및 반납건수를 가짐 (영등포구)
# 2023년 1월 공항시장역 2번출구가 가장 적은 대여건수를 가짐 (강서구)
# 2023년 1월 해공도서관이 가장 적은 반납건수를 가짐 (강동구)

head(df_minmax)

# 구별 대여소 소재지 위치
register_google(key = "AIzaSyC1WQ_4CGx7CTGQ8i3oT23KYpCkihwwup8")
seoul <- get_map("Seoul, South Korea", zoom = 11, maptype = "roadmap")
loc_plot <- ggmap(seoul) +
        geom_point(df_location, mapping = aes(x = 동경, y = 북, color = 소재지))

loc_plot
```